postfix_srv:
  image: emarcs/postfix
  ports:
    - "25:25"
  volumes:
    - ./data/spool/:/var/spool/postfix
    - ./data/log/:/var/log/postfix
    - ./main.cf:/etc/postfix/main.cf
    - ./master.cf:/etc/postfix/master.cf
